/**
 * Artifact identity: whether an attachment was generated by UniZero, and which
 * artifact it is.
 *
 * ZoMiner recognised artifacts by attachment title (fixed strings such as
 * "ZoMiner MD"), which had two consequences:
 *
 * 1. the user renames an attachment → the next conversion cannot find it, creates
 *    another one, and the item ends up with duplicates;
 * 2. the user creates an attachment that happens to have the same name → it gets
 *    **deleted by eraseTx()**.
 *
 * The second is data loss decided by a single string comparison. So ownership and
 * which-one-is-it are separated here, carried by two mechanisms of deliberately
 * different reliability:
 *
 * - **Ownership = tags.** Only attachments carrying a `unizero:` tag may be
 *   overwritten or deleted. Tags travel with Zotero sync and survive a retitle.
 *   This fixes point 2 above and is the load-bearing part of the module.
 * - **Telling artifacts of one kind apart = a record in the attachment note.**
 *   When an item has several PDFs, each produces its own Markdown and the titles
 *   differ only by suffix. Recording the source PDF's key in the note removes the
 *   dependency on titles.
 *
 * The note is reinforcement, not load-bearing: Zotero's handling of note HTML is
 * outside this add-on's control, and if the HTML comment is ever stripped, an
 * unreadable record falls back to distinguishing by title — today's behaviour, so
 * no new regression.
 *
 * There are only four tags in total (one per artifact kind), so they do not
 * pollute the tag selector; they use the automatic type, which lets users hide
 * them there.
 */

/** Generated artifacts use one owned kind per user-visible output. */
export type ArtifactKind = "markdown" | "markdown-copy" | "tables" | "references";

const TAG_PREFIX = "unizero:";

/** Zotero's automatic tag type. Users can hide these from the tag selector. */
const AUTOMATIC_TAG = 1;

/** Record format version; decides how to read old records if the shape changes. */
const RECORD_SCHEMA = 1;

const NOTE_MARKER = /<!--\s*unizero:(\{[\s\S]*?\})\s*-->/;

interface ArtifactRecord {
  kind: ArtifactKind;
  /** Key of the source PDF attachment; distinguishes artifacts under one item. */
  source: string;
  schema: number;
}

export function kindTag(kind: ArtifactKind): string {
  return TAG_PREFIX + kind;
}

/** Whether UniZero generated this artifact — i.e. whether we may overwrite or delete it. */
export function isArtifact(attachment: Zotero.Item): boolean {
  return attachment.getTags().some((tag) => tag.tag.startsWith(TAG_PREFIX));
}

function hasKind(attachment: Zotero.Item, kind: ArtifactKind): boolean {
  const wanted = kindTag(kind);
  return attachment.getTags().some((tag) => tag.tag === wanted);
}

function readRecord(attachment: Zotero.Item): ArtifactRecord | null {
  try {
    const match = NOTE_MARKER.exec(attachment.getNote() || "");
    if (!match) { return null; }
    const parsed = JSON.parse(match[1]);
    if (!parsed || typeof parsed.kind !== "string") { return null; }
    return parsed as ArtifactRecord;
  } catch (error) {
    // The note is unreadable, or not in our format: treat it as having no record.
    return null;
  }
}

function noteFor(kind: ArtifactKind, source: string): string {
  const record: ArtifactRecord = { kind, source, schema: RECORD_SCHEMA };
  return (
    `<p>Generated by UniZero (${kind}). Re-converting overwrites this; do not edit it here.</p>` +
    `<!--unizero:${JSON.stringify(record)}-->`
  );
}

/**
 * Apply the ownership tag, then make a best effort to write the structured record.
 *
 * **Two separate transactions, in this order.** The tag is the only thing that
 * later permits deleting this attachment; if it cannot be written the whole
 * registration should fail, because a silent failure would make the next
 * conversion treat the artifact as the user's own file, refuse to overwrite it,
 * and quietly accumulate duplicates. The note only affects how precisely
 * artifacts are told apart in the multi-PDF case — putting it in the same
 * transaction as the tag would let a reinforcing mechanism veto a load-bearing one.
 */
export async function markArtifact(
  attachment: Zotero.Item,
  kind: ArtifactKind,
  source: string,
): Promise<void> {
  attachment.addTag(kindTag(kind), AUTOMATIC_TAG);
  await attachment.saveTx();

  try {
    // setNote reports failure by return value rather than by throwing; catch both.
    if (!attachment.setNote(noteFor(kind, source))) {
      ztoolkit.log(`artifact note refused for ${attachment.key}`);
      return;
    }
    await attachment.saveTx();
  } catch (error) {
    ztoolkit.log(`artifact note not written for ${attachment.key}: ${error}`);
  }
}

/**
 * Find the artifacts of one kind that belong to us under a parent item.
 *
 * `expectedTitle` only participates when the attachment has no structured record
 * — with a record, the record wins and a retitle changes nothing. This is exactly
 * where renaming stops producing duplicates.
 */
export function findArtifacts(
  parent: Zotero.Item,
  kind: ArtifactKind,
  source: string,
  expectedTitle: string,
): Zotero.Item[] {
  const found: Zotero.Item[] = [];
  for (const id of parent.getAttachments()) {
    const attachment = Zotero.Items.get(id);
    if (!attachment || !hasKind(attachment, kind)) { continue; }

    const record = readRecord(attachment);
    if (record) {
      if (record.source === source) { found.push(attachment); }
      continue;
    }
    // No record: fall back to title matching, the pre-migration way of telling
    // artifacts apart.
    if (attachment.getField("title") === expectedTitle) { found.push(attachment); }
  }
  return found;
}

/**
 * Adopt a pre-migration artifact: add the tag and record so it takes the strong
 * path from then on.
 *
 * Existing users therefore need no migration script — a legacy artifact upgrades
 * itself on the first re-conversion. The cost is having to recognise it by title
 * first, and the misidentification risk of that step is held down by the caller's
 * stricter preconditions (see the legacy check in conversionAdapter).
 */
export async function adoptArtifact(
  attachment: Zotero.Item,
  kind: ArtifactKind,
  source: string,
): Promise<void> {
  ztoolkit.log(`adopting legacy artifact ${attachment.key} as ${kind}`);
  await markArtifact(attachment, kind, source);
}
